services:
  db:
    image: postgres:15.4
    container_name: postgres_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: shop
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer  # Замість конкретного тега
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  postgres_data:
